# Catppuccin Macchiato - Soothing pastel theme for the high-spirited!
name = "catppuccin-macchiato"
description = "Catppuccin Macchiato (dark theme)"
foreground = "#cad3f5"
background = "#24273a"
accent = "#8aadf4"
strong = "#ed8796"
dim = "#6e738d"
ascii_art_style = "bold"
